# Generated by Django 6.0.1 on 2026-01-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StdentModelClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('std', models.CharField(db_index=True, max_length=20)),
                ('sub', models.CharField(db_index=True, max_length=50)),
            ],
        ),
    ]
