# Generated by Django 6.0.1 on 2026-01-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModelClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='stdentmodelclass',
            name='teacher',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='nestedapp.teachermodelclass'),
            preserve_default=False,
        ),
    ]
