# Generated by Django 6.0.1 on 2026-01-12 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0002_teachermodelclass_stdentmodelclass_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stdentmodelclass',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teachermodelclass',
            name='teacher',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='nestedapp.stdentmodelclass'),
            preserve_default=False,
        ),
    ]
