# Generated by Django 6.0.1 on 2026-01-13 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0003_remove_stdentmodelclass_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllSerializerFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('fees', models.DecimalField(decimal_places=1, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('dob', models.DateField()),
                ('joining_time', models.TimeField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='teachermodelclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='nestedapp.stdentmodelclass'),
        ),
    ]
