# Generated by Django 6.0.1 on 2026-01-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestedapp', '0004_allserializerfieldmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdentmodelclass',
            name='std',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stdentmodelclass',
            name='sub',
            field=models.CharField(max_length=50),
        ),
    ]
